project_id = "rfkdcmvzvxcsoecoeddi"

[functions.send-contact-email]
verify_jwt = false

[functions.reformat-single-article]
verify_jwt = true

[functions.import-and-process-all]
verify_jwt = true

[functions.translate-locales]
verify_jwt = false

[functions.generate-batched-sitemaps]
verify_jwt = false

[functions.serve-sitemap-index]
verify_jwt = false

[functions.serve-sitemap]
verify_jwt = false